FROM python:3.12-slim-bookworm

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# Copy the project into the image
WORKDIR /app
COPY pyproject.toml .
COPY uv.lock .
COPY settings.toml .
COPY alembic.ini .
ADD src ./src
ADD alembic ./alembic

# Sync the project into a new environment, using the frozen lockfile
RUN uv sync --frozen

# Run the web app
CMD ["/app/.venv/bin/fastapi", "run", "/app/src/main.py", "--port", "80", "--host", "0.0.0.0"]
