FROM python:3.14-alpine AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev

FROM python:3.14-alpine

WORKDIR /app

COPY --from=builder /app/.venv /app/.venv

COPY alembic.ini .
COPY src ./src
COPY alembic ./alembic

ENV PATH="/app/.venv/bin:$PATH"

RUN adduser -D appuser
USER appuser

EXPOSE 80

CMD ["fastapi", "run", "src/main.py", "--port", "80", "--host", "0.0.0.0"]