"""vote model

Revision ID: 0eb43ad4bc6a
Revises: 4bba09b076c2
Create Date: 2025-05-09 21:54:36.716947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0eb43ad4bc6a"
down_revision: Union[str, None] = "4bba09b076c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

vote_reports_enum = sa.Enum("a", "b", "c", "d", "e", name="reports")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    vote_reports_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "vote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "report",
            vote_reports_enum,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vote")
    vote_reports_enum.drop(op.get_bind, checkfirst=True)
    # ### end Alembic commands ###
