"""vote model code unique

Revision ID: 2c14278aa4c9
Revises: 0eb43ad4bc6a
Create Date: 2025-05-10 02:47:17.479940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2c14278aa4c9"
down_revision: Union[str, None] = "0eb43ad4bc6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vote", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_vote_code", ["code"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vote", schema=None) as batch_op:
        batch_op.drop_constraint("uq_vote_code", type_="unique")

    # ### end Alembic commands ###
